# backup.conf

# Source and Destination
SOURCE_DIR="/home/ybryshten/linux_practice/important_database"
DEST_DIR="/home/ybryshten/linux_practice/backups"

# Retention policy (in days)
RETENTION_DAYS=7

# Where to save the backup logs
LOG_FILE="/home/ybryshten/linux_practice/backups/backup.log"

EMAIL_TO="ybryshten@griddynamics.com"